version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
  - package-ecosystem: "npm"
    directory: "/sdk/nodejs"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "sdk/nodejs"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "area/website"

  - package-ecosystem: "gomod"
    directory: "/sdk/go"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "sdk/go"

  - package-ecosystem: "pip"
    directory: "/sdk/python"
    schedule:
      interval: "daily"
    labels:
      - "kind/dependencies"
      - "sdk/python"
