project_name: dagger

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/dagger
    binary: dagger
    ldflags:
      - -s -w
      - -X dagger.io/go/cmd/dagger/cmd.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
- name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  replacements:
  files:
    - LICENSE
    - README.md
    - doc/**/*
    - examples/**/*
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
- tap:
    owner: dagger
    name: homebrew-tap
  commit_author:
    name: dagger-bot
    email: noreply@dagger.io
  homepage: "https://github.com/dagger/dagger"
  description: "Dagger is a programmable deployment system."
  test: |
    system "#{bin}/dagger version"
