[build]
  base = "tools/daggosaurus/"
  publish = "build/"
  command = "yarn build"
  # build only if there are changes within daggosaurus or docs directories.
  ignore = "[ $BRANCH != main ] && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../docs/"
