[build]
  base = "website/"
  publish = "build/"
  command = "yarn build:withoutAuth"

[context.production]
  # Do not build the site if there's no site-related changes since the last
  # commit.
  # This assumes PRs to `main` only contain merge commits, so it's safe to
  # compare the current commit to the previous.
  # We can't use `$CACHED_COMMIT_REF` because that points to the PR preview
  # that was built before merging.
  ignore = "git diff --quiet HEAD^ HEAD -- . ../docs/ ../netlify.toml"

[context.deploy-preview]
  # Do not build the site if there's no site-related changes since the last
  # deploy.
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../docs/ ../netlify.toml"

[[redirects]]
from = "/github-proxy/*"
to = "https://github.com/:splat"
status = 200

[[redirects]]
from = "/github-api-proxy/*"
to = "https://api.github.com/:splat"
status = 200

[[redirects]]
from = "/docs-access/*"
to = "https://j20f3pfq11.execute-api.us-east-1.amazonaws.com/Prod/u/:splat"
status = 200

[[redirects]]
from = "/reference"
to = "/reference/universe/alpine"
status = 302
