plan:
    package: ./docker/tests/command-ssh
name: docker-command-ssh
inputs:
    TestConfig.host:
        text: 137.184.58.110
    TestConfig.key:
        secret: ENC[AES256_GCM,data:y+EideEd0sTJ4FF0L8neepRT79T8GtE95dGNywkkG9EV6G81ewwyfkAQsF0Lgdtf/Lziqa/v/8xBQJwnfjTAqFi+qHPYvKjXAqgUyfeHSPTvHWudL4ELHcIu/4YvvUYOu5oaOSxeeb8qElZ2id9GyFBV2cJVywfHBagAdGuejnVKfHSMyZLc6Dxdpa+QZt8srPv4ZPnJUN6s7tOC0IgDESsRBFSgSE5ld4smb84QbP1bfNzSPW1Jq+vo1EmoTJgMjsOkjSDfXC0+rLdpHf958ZPLZuM5L86hx8BHauQZ1v3qNXChPNFbEbhEO7yrFAWlXc2GqvDrhAJlTYo+Xl6NPpE3cixcwgFtwEc3EHln4AaRxs9UZnx8s8qZ7Ys4iGU9nWdnWYIdPTxtcFjU7hdTcSYxCfDZMLYozT/9cyKaOUtI3TW3+bEgXUu6Zn6ABpcIZjf6ZjjfPXtS0cpKd7wCWMXGgPozO+PayFgJndJJteEDQb55r5oSaLbajpmrlrRNOXxJsGNhTBke9PSdJ3DGCS6iYigDsQ7S3mYW,iv:jKm2y1zzH2kvPkuDnJRNa8l05Nwbc9bf3IPKhMwRdVM=,tag:xDevSihBxMI4eOTb2iGREA==,type:str]
    TestConfig.user:
        text: root
    TestPassword:
        secret: ENC[AES256_GCM,data:8G7Cgw==,iv:+hlWzOxy4H9OYwP0x+7LIMFhQoebmP3yUGRuhPSGGgI=,tag:i+dHE+W2zud5xGvWL5PxVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSU5uMDBNdDEzQXFsb2ZS
            VDRDai9yOHFPSnI4dXhDY0FUcXVkRXdMMXdBCnhSTER5bEJRRDNZbStVTTk5d2FN
            MUxkM1JpQ3NHa3B4MHlnZ1dDU1RoS2cKLS0tIE9Xa1ovQkRSZlBZMjZlZi9OUGhG
            UEpoZy9HZUlHOVV3M05OSkZQS1l6aXcK3NfBITvd6la6nkcIzqH69xfv9RR0Jm7x
            vU5FvGROK3Z0ZR8NNXAtNH6VQQ21TDD2MOXWOVvjnIAAOVNEyc1amA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T21:13:07Z"
    mac: ENC[AES256_GCM,data:QHSy5Vryhe3G4OS6GRs0t24VuG2HKbka+WuC03CKTOaHlpE9K1l0kuXtFpEzGGxmYs8FKUW2Gb+K3HSP6L/w3T0D0jY9fvSMrX7anQUCzIqRlzxQiQ+ZYueeV9Nr8hF78QfN8Ix+vY03u7KaAWzc0+yHtxRsDAPGjArvrG4+vBs=,iv:ni2u3M1EUsz3wndefGxdhX4Q/KwcZ+FZaFgKhRep22w=,tag:LC3KBS+ijbn01HzSyySQDw==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
