plan:
    package: ./docker/tests/command-ssh-wrong-key-passphrase
name: docker-command-ssh-wrong-key-passphrase
inputs:
    TestConfig.host:
        text: 137.184.58.110
    TestConfig.key:
        secret: ENC[AES256_GCM,data:9H5WgztxyzMQPtXFvCOdjTDx9XXoGmF2C+Ml9GD51EDCMMSgmMSGnHn1R4iB3fF8phkKqI8izvPf1yJxuAJVy7RuY0SvysSGSUKncwNM7tZ0Ca/ItZx9rcQfViE44sN0Bhy5PtiEP/CfyCYzQfytjZL1AvnXLktKwuwtXOFPR9CgUtBCU3pgXlAfu23Yiko4L0RjzTVqai+T7BC5tjQXLVG3CzQexj7eo/QsrQoM3PZMWlANg8xSnjQabkfjmREN6TcCM1YsLNLEnBOZwbh3qpBuoDBmoc8WLQlNWALh4kRZgyMwvNlXRMK4I+BZ/GSo4gRvAHXEtDNbCPNINcOb3/j3yPnxNvBdLR4fSfHInvrgM4fcPmgMaJOMhFhR6i+f+La/JnNmwTSPnISh7p8gDsBRbRxZoTlCjGf9v30Bg9KQqSsFu5vsmnAB8+dbnqiyaPyz4TuoRPA0rnx0JQDIDbX1cntFV2o/HVQlPLpcNx2mSoFiAKpapjowOkcCghTFWP+unRdubCr9wVEzmkRkQHgvIsOwzQjPBGX+bQF9vCf+8HZ/qBWxFaQMHTpIWAMXUTf2QNawvZQkj2RWoh7zG5cD3y8JTEUCD+2eUXedx3k=,iv:9nBZTTbL/mvR/Sy9W+ozDWeoEfrGYxtm1wxIbx53HqY=,tag:KbOHlBNJlMZgpUi9AEbKSA==,type:str]
    TestConfig.keyPassphrase:
        secret: ENC[AES256_GCM,data:1VJ0/g==,iv:4zm6VTnb29Sb/a+FXQ0vqF79vjbjVTdmHMNdgftjV7M=,tag:E5D/qDpFY5cTRhWKvp3YCQ==,type:str]
    TestConfig.user:
        text: root
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U0w2S2luTlJNbGhnd3FY
            dmp4K2t6ZWR1Q1dYNCsvRWhZRkl4UWFoVEhRCmZHUHNBVW5LZEl1ckpGQmJlZEVP
            LzEweFZrbWZoMDhBbGQ3eXdrbGtoNzAKLS0tIEhoWXZidi9yejFjaTlCOGo4Q1Bl
            R2tNU2JJWHFQTmhnUDd6eE13UUhQazgK+OQ50Q3+S5Fn2Y132ZeDrgUKWPcAk+et
            q8ppfZiPOtH4p6MwboSuh/vaTAAsxks7ctnqnU1pY+EHfnp8bHYHgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T22:46:36Z"
    mac: ENC[AES256_GCM,data:Bc7LmOx1lEb4K+BszbT35YClp+C4euJaZzzHkEYqxXRT/+CErRYH7vChk+6ewfMP/NZzg4lfuCK2mGfl4c3yB251sjEv0hvMqkLn4lCDBSnAkIO4EnpbGPvHNctB/GY3XrXFNM/AQ4Ez2mNUDchuJAQkw3FmOkMsP2jE7ZIDf0Y=,iv:x7J0gtt1WwWzMFgaTuMYQuOlNM9MgzUjMIQ+P9ibbIM=,tag:fKOf/x9XsIFixWg1RaN00w==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
