plan:
    package: ./git/tests/commit
name: git-commit
inputs:
    TestAuthToken:
        secret: ENC[AES256_GCM,data:1F5Km+lgtvwkMIOoNRvnjbxUkeFp7xgNrk20Rbd0vlJGFurHpwSO6g==,iv:DgwDFxbMs80U8ICOdAWIWfPy9BLIzM6sSPHXe5gE+y8=,tag:sQ0al8wERZdvtgUZYe4pTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWkIxUExFTnQ2VS9pSHVv
            Ykd6eUl4dlRQeU9YRGtLQWhPNExZakZORG5VCkVLN3NnNlNxZ0hmQW9TRGU5WXpN
            UmYzZE1BUWZ1WDlPWjA2dURIbDA1bGcKLS0tIHBkR3c2U3IxY2w5Z0YxOWxLRkVv
            M3RnUDF5QlhhZUV4NHF5ZWhkcHVrNmcKUJIummOk3FX1Bert7gaMtbMpbosIf/d3
            HBATJRng4VNmcSimSh14pDRxyW0NdIPA+oL4tidwLVbQQv/74+IGKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T17:48:06Z"
    mac: ENC[AES256_GCM,data:EamKomihsz84e/FyyVRAOAxzI1CsWstMfTa4DDIouO/7Z3+70KLm82IfS/FAiv8dYhj8d7z13JFXCJIpaBwalt7KhagCGza8xcaEMteDvO17SPwhD82mZNqmxmiv6504UXhjRoG5nF/uRRC6WDmt6IAFtEHWfdw44Hu1PMAlhaM=,iv:Pr+RgNvQTRjEHop1BKbAJ4ASZRj8wox7pmlpUeUGk9Y=,tag:FXrUTLYQLSxPajQ+MoKmLw==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
