[build]
  publish = "build/"
  command = "yarn build"
  environment = { NODE_VERSION = "16.13.1" }

[context.production]

[context.deploy-preview]
  command = "yarn build:withoutAuth"

[[redirects]]
  # Embargoes compliance. DO NOT REMOVE
  conditions = {Country = ["CU", "IR", "KP", "SY", "UA"]}
  from = "/*"
  to = "/restricted"
  status = 302
  force = true

[[redirects]]
from = "/github-proxy/*"
to = "https://github.com/:splat"
status = 200

[[redirects]]
from = "/github-api-proxy/*"
to = "https://api.github.com/:splat"
status = 200

[[redirects]]
from = "/docs-access/*"
to = "https://j20f3pfq11.execute-api.us-east-1.amazonaws.com/Prod/u/:splat"
status = 200

[[redirects]]
from = "/t"
to = "https://api.amplitude.com"
status = 200

[[redirects]]
from = "/reference"
to = "/reference/alpine"
status = 302
