name: docs
inputs:
    docs.env.REACT_APP_CLIENT_ID:
        text: 1a6d02cb59199eb205ef
    docs.env.REACT_APP_CLIENT_SECRET:
        text: 47a1a67abc8d3fe9edb829a6c7775fbad47f47bb
    repository:
        dir:
            path: .
            exclude:
                - '**/node_modules'
                - cmd/dagger/dagger
                - cmd/dagger/dagger-debug
    site.account.name:
        text: blocklayer
    site.account.token:
        secret: ENC[AES256_GCM,data:jPJ8N6cAmtYnQh2SyhM9bQGfkhz777S4fyPDm2YhujwgXH6EogN2Uyw6Ew==,iv:gDchoJYLdQ8IPxrUUIsQ9s2f12JOhh7p573DwOIV2zE=,tag:okatHyjVGPGNOt+aw4iUHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZVVuYThsYk9YcWhYb0g4
            TDhZQ21YN0FCRExKV2tqbVVUNTg5MWRUVUJzCndjc28yVUZEK3ZoQzVDQkk4emZQ
            WGx2bUxSZlBENXlibzQ1MVkvc2I2MVkKLS0tIFJKS0ZENFhuVmdUM2h1a2xrK01a
            ejRKQXNFZzBTbUxpc05acnkxQ2U2UkEKX1byNj64xOiRGAJ9lwh55d/mlasI3H6H
            b+o3HbXSbV0G0UwQxEOisntR6o27ry/l12ai/sOQ4f9MXm6FRw2XTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-06-15T07:57:28Z"
    mac: ENC[AES256_GCM,data:PPeh8uZ4i8kRqgoDMLBlHMy3jFs0jQxJKdkeA3LTqbBKZ9EEEt9K4ASmZVbTUv5iumcoxaXc2u6ty0gDPaLjqnYPLMOzR962+5ipp96l1fzA7vvNpdNlUPweTo6WgQUBf/J4eOPBlm3O2pPi7Os+IlvnvM92ZL6Y9K3oOZqlnwU=,iv:Mz8jz3lBOEVqlqKEaqa5ujecr4B/IIaeW34Kx3cEwwE=,tag:feixK5kYE61WeEzJcXjRoA==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
