name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.6
        id: go

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends shellcheck
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sudo sh -s -- -b /usr/local/bin v1.23.8
          curl -L https://github.com/cuelang/cue/releases/download/v0.3.0-beta.3/cue_0.3.0-beta.3_Linux_x86_64.tar.gz | sudo tar zxf - -C /usr/local/bin

      - name: Check out
        uses: actions/checkout@v2

      - name: Build
        run: |
          make

      - name: Lint
        run: |
          make lint

      - name: Start buildkit
        run: |
          docker run -d --name buildkitd --privileged moby/buildkit:v0.8.1@sha256:ecd5ad4910c322cad6995f8a1a0805d9da4b09ed4aaef40627f5bcb8ebf74068

      - name: Integration test
        run: |
          make integration

      - name: Test
        run: |
          make test
