name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semver.outputs.next }}
          message: ${{ steps.semver.outputs.next }}
