name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          branch: main
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semver.outputs.next }}
          message: ${{ steps.semver.outputs.next }}
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
