name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  # Enable manual trigger for easy ad-hoc debugging
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch:
jobs:
  go:
    name: go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go test -race -timeout=30m -v ./...
