plan:
    package: ./docker/compose/tests
name: docker-compose
inputs:
    TestSSH.host:
        text: 137.184.58.110
    TestSSH.key:
        secret: ENC[AES256_GCM,data:Q3rJqH6p2t315up5R0XjPFy8fastZ3nEes4ZGFCIZhI/ULo+4PCMeVubJJ30mJcseMMRj8EA89PrKmQeualQNWYEB3ytNi/OZwvXmCGKmnmAwAg9jGBskWGvyh7s5tztWF9DVTFqhK3lQV5wF9PNrTVBbHRrDWWO5AQVIFakDsMCbSB5Tmvjo0QYqq2DBBEK8k3aH34srn1f2no1ih8DidP3o9VqvSl7t0US+okT7B3V+v0N0B0/kRQrtgfv5WXx10TUWAxySRmLofIsWPH2EXjzdFEo5S4tk8I2nxGMPladNzuMe4LX+er2uqf7iE578K+XoVePq2Bdn6yBeqK3votaFT+D6qC0e112IW8a1nHxX2taKCCY11EKr18ZWvj0YYwjvca/tdqjzSq+SqSEaLiNtrrPINriER76SNzxZcTBTBY1lYA3IYhNzF67DQBh9di+beh5Lyb6nOV77zLXm7K8l7dlYSm6piAHyJZt/LZwgQFDAVv/F6x8zqLPclXJodR+z5yrHhtHFlqCCTNpp1trL6wXaOl3MNxo,iv:GXOAMgvBnyedRMG2izQBPDxjdsjkJ9FUi1BQJeRFoBw=,tag:FJtPBv+q5hGfcR3gTmEIPg==,type:str]
    TestSSH.user:
        text: root
    repo:
        dir:
            path: ./docker/compose/tests/testdata
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSmROdEtUblF3REhwS3hC
            bU9ObTE0aWQzdGJzRlB5WjA0UG5nZFFJTEJjClljQWFYYWNQaFozZGRMcWxyT3p3
            Y0ZVUlZISUNlVkxVSVBqY0RRaGxPN3cKLS0tIGhsUTFCK2ljaWZFekVQMlRSRmtD
            bEY3N3ZLTFpUNzZVWVBOK3VNRk9hWlUKd9db3j7FqFW4t7TxFyzudKDPTVqr66v2
            KqedhRYCjF4ZozN0H++xQPH24RBRnwc6Uq0Vm38UYv1ozDN2L/l5DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-26T16:47:21Z"
    mac: ENC[AES256_GCM,data:tpXsVPpzLBMF5ytMumpl3D/lbxMCy9CLhFkJ8xFYwUmoCKIxWHAyXBcUO4Yn3B4NVrShnAXm5U6ctQYBNLQh7sMAuakeOzlDU9E3sK+drFlwW5iuddCH5ksjCPKNIdOKt7+i6O+984iJs1xHLNdsOsyB0bH814RFBLACSv+gHls=,iv:KL9W6YS5T864wGOS4ONdHTOASmDBZerL6TaaBf7zrQI=,tag:x5/Lr7OovvbaWQoMWx7z5Q==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
